-- Execute este SQL no Supabase > SQL Editor

create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  name text not null,
  score integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.ranking enable row level security;

drop policy if exists "ranking_select_public" on public.ranking;
create policy "ranking_select_public"
on public.ranking
for select
to anon
using (true);

drop policy if exists "ranking_insert_public" on public.ranking;
create policy "ranking_insert_public"
on public.ranking
for insert
to anon
with check (
  char_length(name) between 1 and 40
  and score >= 0
);

create index if not exists ranking_score_created_at_idx
on public.ranking (score desc, created_at asc);
